
export default [
  {
    id: 1,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Ingeniero TI',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"catamuñoz@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"fermaldonado@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 2,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Marketing',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 3,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    
    createdAt: 1555016400000,
    nombre: 'Obras Civiles',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 4,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Ingeniero TI',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 5,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Marketing',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 6,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    
    createdAt: 1555016400000,
    nombre: 'Obras Civiles',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 7,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Ingeniero TI',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 8,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Marketing',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 9,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    
    createdAt: 1555016400000,
    nombre: 'Obras Civiles',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },{
    id: 10,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Ingeniero TI',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 11,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    createdAt: 1555016400000,
    nombre: 'Marketing',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
  {
    id: 12,
    status: "status",
    below: "5",
    normal: "6",
    outstanding: "7",
    
    createdAt: 1555016400000,
    nombre: 'Obras Civiles',
    candidatos: [
      {
        nombre:"Benjamín González",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Catalina Muñoz",
        ciudad:"Viña del mar, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
      {
        nombre:"Fernanda Maldonado",
        ciudad:"Stgo, Chile",
        profesion:"Ing. Civil Industrial mención TI",
        experiencia:"Exp: 3.5 años",
        email:"bgonzalez@myfuture.ai",
        universidad:"Universidad Adolfo Ibáñez",
        numero:"+569 54191544",
        egreso:"Egreso: 2017",
        trabajadoen:["uplanner","fractal-BI","future-AI"],
        skills:[" Django, python, API, devops"," Tensorfow, NLP, deeplearning","Machine Learning, Ofce"],
        trabajadocomo:["Consultor/ BI Analyst"," DataScientist"," Lead DataScientist / Backend develop"],
        idiomas:["Inglés avanzado","Español"],
        certificaciones:["Diplomado en transformación digital"],
      },
    ],
  },
];
