# Generated by Django 3.1.2 on 2020-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
