# Generated by Django 3.1.2 on 2020-11-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_last_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_token',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
