# Generated by Django 3.1.2 on 2020-11-17 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=100)),
                ('subarea', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('vacant', models.IntegerField()),
                ('requirements', models.JSONField(null=True)),
                ('desired', models.JSONField(null=True)),
                ('kpis', models.JSONField(null=True)),
                ('storage_url', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_from', models.CharField(max_length=100)),
                ('value_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_id', models.ManyToManyField(to='selection.UserConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('info', models.JSONField(null=True)),
                ('selection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.selection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
