# Generated by Django 3.1.2 on 2020-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
