# Generated by Django 3.1.2 on 2020-11-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_selection_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='vacant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
