# Generated by Django 3.1.2 on 2020-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_auto_20201117_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='value',
            field=models.CharField(max_length=5000),
        ),
    ]
