# Generated by Django 3.1.2 on 2020-11-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_auto_20201117_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='selection_id',
            new_name='selection',
        ),
        migrations.RenameField(
            model_name='changeitem',
            old_name='config_id',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userconfig',
            old_name='user_id',
            new_name='user',
        ),
    ]
