# Generated by Django 3.1.2 on 2020-11-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20201118_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='count',
        ),
    ]
