# Generated by Django 3.1.2 on 2020-11-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_remove_selection_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeitem',
            name='config',
        ),
        migrations.AddField(
            model_name='changeitem',
            name='field',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
