# Generated by Django 3.1.4 on 2020-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='desired',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='kpis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='storage_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
