# Generated by Django 3.1.4 on 2020-12-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0009_auto_20201218_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
